# Generated by Django 5.0.4 on 2024-05-07 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=255)),
                ('jobsalary', models.IntegerField(default=0)),
                ('jobstatus', models.CharField(max_length=255)),
                ('yearsofexperience', models.CharField(max_length=255)),
                ('companyname', models.CharField(max_length=255)),
                ('companyaddress', models.CharField(max_length=255)),
                ('jobdescription', models.TextField(default='')),
                ('jobrequirements', models.TextField(default='')),
            ],
        ),
    ]
