# Generated by Django 5.0.4 on 2024-05-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_delete_userregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
    ]
