# Generated by Django 5.0.4 on 2024-05-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_job',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_link',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_description',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resume_link',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.CharField(blank=True, default='N/A', max_length=255, null=True),
        ),
    ]
