# Generated by Django 5.0.4 on 2024-05-24 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='current_job',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='resume_link',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_id',
        ),
    ]
