# Generated by Django 5.0.4 on 2024-05-25 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_userprofile_current_job_and_more'),
        ('authentication', '0004_user_current_job_user_picture_link_and_more'),
        ('jobs', '0002_jobs_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
