# Generated by Django 5.0.4 on 2024-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_jobapplication_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
