# Generated by Django 5.0.4 on 2024-05-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_jobapplication_job_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='jobapplication',
            constraint=models.UniqueConstraint(fields=('user_id', 'job_id'), name='unique_user_job_application'),
        ),
    ]
