# Generated by Django 5.0.4 on 2024-05-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_jobapplication_unique_user_job_application'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobapplication',
            name='unique_user_job_application',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
