# Generated by Django 5.0.4 on 2024-05-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_remove_jobapplication_unique_user_job_application_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
