# Generated by Django 5.0.4 on 2024-06-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_alter_jobapplication_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
