# Generated by Django 5.0.4 on 2024-06-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0011_remove_jobapplication_job_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='user',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
